docs/api/index.rst
docs/tutorials/tut_intro.ipynb
starsim/network.py
starsim/products.py
starsim/random.py

More fixes to get the docs build working

Fix docs build

---

docs/_templates/page.html

This adds the Google Tag Manager container so we can get analytics on docs usage.

Update page.html to add Google Analytics

---

docs/conf.py

Small fix for the url in documents config.py file.

Fixing github url for starsim

---

docs/_templates/footer.html
docs/_templates/footer_end.html
docs/_templates/footer_start.html
docs/conf.py

Fix footer

---

docs/tutorials/dev_tut_diseases.ipynb
docs/tutorials/tut_interventions.ipynb

https://docs.idmod.org/projects/starsim/en/latest/tutorials/dev_tut_diseases.html 
Add a line right before the list.
This is what we are expecting to see:

Fix to missing lines and some typos on tutorials.

---

starsim/diseases/sir.py
starsim/distributions.py

Adds an `immunity` state to the SIS model, and closes #443 .

Update SIS model and slots fix

---

CHANGELOG.rst
starsim/diseases/syphilis.py
starsim/version.py

According to our syphilis expert consultant, mucosal shedding of T pallidum bacteria may occur during latent phases of infection. This PR allows sexual transmission of syphilis during latent phases. Parameter values for the relative transmissibility are currently placeholders.
Closes https://github.com/starsimhub/starsim/issues/429

Latent syphilis

---

starsim/demographics.py

Accounting for dt in calculation of crude birth and death rates

Fix crude rate reporting

---

starsim/demographics.py
starsim/disease.py
starsim/diseases/cholera.py
starsim/diseases/gonorrhea.py
starsim/diseases/hiv.py
starsim/diseases/ncd.py
starsim/diseases/sir.py
starsim/diseases/syphilis.py
starsim/distributions.py
starsim/interventions.py
starsim/network.py
starsim/parameters.py
starsim/people.py
starsim/products.py
starsim/run.py
starsim/samples.py
starsim/settings.py
starsim/sim.py
starsim/states.py
starsim/utils.py

Added return statements to functions where missing and ensured that function and class blank lines were consistent with Python standards. Reviewed and updated codebase for consistency with Python Google and Pep8 standards.
[Python Standards Checklist.docx](https://github.com/starsimhub/starsim/files/15028566/Python.Standards.Checklist.docx)

Python standards

---

contributing.rst

Updated links; and replaced STIsim with Starsim

Minor fixes to contributing.rst

---

starsim/demographics.py
starsim/disease.py
starsim/diseases/sir.py
starsim/diseases/syphilis.py
starsim/distributions.py
starsim/interventions.py
starsim/modules.py
starsim/network.py
starsim/parameters.py
starsim/people.py
starsim/sim.py
starsim/states.py
starsim/utils.py
starsim/version.py

Implement transitions

---

starsim/demographics.py
starsim/sim.py
tests/baseline.json
tests/benchmark.json

* Normalizing `update_results` function for demographic modules, resolving #497.
* Also found and fixed a bug in the uids that are used to choose birth sex from pregnancy.

Demographic update_results normalization

---

docs/_static/theme_overrides.css

.css file - footer update (smaller font)

.css file - footer update (smaller font)

---

README.rst

Update read me for pypi

---

starsim/demographics.py
starsim/network.py

Simple update to ensure unsure agents cannot become pregnant.

Ensure unborn agents cannot become pregnant.

---

starsim/parameters.py

Fixing warning message and handling callables.

---

starsim/demographics.py
starsim/disease.py
starsim/diseases/cholera.py
starsim/diseases/ebola.py
starsim/diseases/gonorrhea.py
starsim/diseases/hiv.py
starsim/diseases/measles.py
starsim/diseases/ncd.py
starsim/diseases/sir.py
starsim/diseases/syphilis.py
starsim/results.py
starsim/sim.py
tests/test_diseases.py

- Added label to the Result class (#510) 
- Update existing definitions of States to have accompanying labels 
- Update plot function of sim to leverage the new results labels
I am not sure if I should split the updates to existing modules to another ticket? Also, I am not 100% confident in my labels, so extra attention would be greatly appreciated. 
TODO: Update tests to include results

Add label to results Class

---

starsim/network.py

Used manual numpy calculation instead of scipy distance matrix for considerable time savings.

Faster disk graph implementation

---

starsim/diseases/hiv.py
starsim/network.py

Making delay to ART initiation a user-configurable distribution that adapts with `dt`.

HIV ART delay

---

starsim/people.py

Matches syntax expected by sciris.dataframe.from_dict noted in #618

address TypeError calling Person.to_df function #618

---

starsim/run.py

Fixes a minor bug with allowing figures to be passed into MultiSims.

Fix msim plotting

---

starsim/calibration.py
starsim/sim.py

- Adds a check to skip product initialization if product is None
- Minor tweaks to calibration

Edits for stisim

---

starsim/distributions.py
starsim/networks.py

Replacing random rounding with a binomial draw

Addressing stochasticity in Births related to dicussion in Unstable Vital Dynamics #695

---

starsim/time.py

Addressing an issue reported by @skroiss-idm, #788

Addressing Indexing error when burning in pregnancies #788

---

starsim/calibration.py
starsim/interventions.py
starsim/results.py
starsim/sim.py
starsim/version.py
tests/test_demographics.py
tests/test_other.py
tests/test_run.py

Fixes https://github.com/starsimhub/starsim/issues/700. 
Example:
```
sis = ss.SIS(unit='month')
sim = ss.Sim(diseases=sis, networks='random', n_agents=medium)
sim.run(verbose=0)
sim_df = sim.to_df(resample='year', use_years=True)
```
Returns a dataframe where the monthly values have been aggregated to an annual dataframe.

Self-summarizing results

---

starsim/demographics.py
starsim/results.py
tests/test_other.py

Adds explicit summary methods for demographic modules

Results addition

---

CHANGELOG.rst
docs/requirements.txt
starsim/calibration.py
starsim/results.py
starsim/sim.py
starsim/version.py

Fixes `shrink()`. Closes https://github.com/starsimhub/starsim/issues/863 and https://github.com/starsimhub/starsim/issues/857.

Fix shrink

---

starsim/calibration.py

Separating to_df and save_csv

---

CHANGELOG.rst
LICENSE
docs/conf.py
docs/requirements.txt
starsim/calibration.py
starsim/networks.py
starsim/results.py
starsim/sim.py
starsim/time.py
starsim/version.py

Version 2.3.1

---

CHANGELOG.md
README.md
code_of_conduct.md
contributing.md

Convert root RST files to Markdown

---

starsim/distributions.py
starsim/modules.py
starsim/people.py
starsim/sim.py
starsim/time.py
starsim/version.py

PHCsim fixes

---

starsim/demographics.py
starsim/networks.py

Mixing pools

---

starsim_examples/laser/laser_example_orig.py
starsim_examples/laser/laser_starsim_full.py
starsim_examples/laser/laser_starsim_minimal.py

Rc3.0 laser

---

starsim/distributions.py
starsim/loop.py
starsim/modules.py
starsim/parameters.py
starsim/sim.py
starsim/utils.py
starsim_examples/laser/laser_example_orig.py
starsim_examples/laser/laser_starsim_full.py
starsim_examples/laser/laser_starsim_minimal.py

Adds `modules` as a sim argument and attribute, allowing more flexible simulation types (including adapting LASER models).

Rc3.0 jul08

---

starsim/arrays.py
starsim/demographics.py
starsim/diseases.py
starsim/modules.py
starsim/people.py
starsim/settings.py
starsim/sim.py
starsim/utils.py
starsim_examples/diseases/cholera.py
starsim_examples/diseases/ebola.py
starsim_examples/diseases/gonorrhea.py
starsim_examples/diseases/hiv.py
starsim_examples/diseases/measles.py
starsim_examples/diseases/sir.py
starsim_examples/diseases/syphilis.py

Updates states, including renaming `ss.State` to `ss.BoolState`, adding `ss.IntArr`, and moving more operations to `ss.Module`

Rc3.0 states

---

starsim/distributions.py

Add beta distribution

---

starsim/timeline.py

Change year to yearvec
