starsimhub/starsim

starsim/demographics.py
Seems straightforward unless someone is using `conception_probs` elsewhere?
=> Remove unused `conception_probs` from Pregnancy

starsim/diseases/cholera.py, starsim/diseases/ebola.py, starsim/diseases/gonorrhea.py, starsim/diseases/measles.py
Adding dt to disese modules. Note, did not sc.randround to an exact ti, but rather left ti as a float computed as sim.ti + duration/sim.dt. This is in part because randround is not crn safe. The check is if event_ti < sim.ti, so by not rounding, events will be shifted to the next timestep. Hopefully dt is small enough relative to duration that this doesn't really matter.
=> Adding dt to disese modules

starsim/demographics.py, starsim/distributions.py, starsim/sim.py, tests/baseline.json, tests/benchmark.json
1. Bernoulli (binomial) random variables don't use a random number when p=0, throwing off CRN. Small/hacky fix for that issue.
2. In demographics, better handling of age bins that was causing a bug in some cases.
3. Correct length of sim yearvec for dt != 1.
=> Three bug fixes

starsim/people.py
Trivial one-line change to avoid a warning (or error?) in converting int to float.
=> Fix type conversion in age_props

starsim/network.py
Important change to the duration of edges in RandomNet. Results using RandomNet will change as the default edge duration has changed from one year to zero, which means one time step. 
The implementation still needs a rework so that results do not vary with dt.
=> Change RandomNet edge duration

starsim/demographics.py, starsim/distributions.py, starsim/settings.py
Restoring the ability to use a centralized random number generator, as needed for the CRN publication. Can remove later.
=> Restoring the ability to use a centralized RNG

starsim/modules.py, starsim/products.py, starsim/sim.py
I ran into issues with multiple interventions using the same product. For each intervention using that product, it was previously trying to initialize the product and add it to the people class. 
I added a `def initialize(self, sim)` method to the `ss.Product` class to ensure the product only gets initialized once.
And I moved `self.people.add_module(intervention)` to the module initialization and removed it from `sim.py`. This way, the module is responsible for adding itself to the people class.
=> Multiple interventions using the same product

starsim/disease.py
Allows passing arguments to parent constructors e.g., to be able to set the `name` attribute
=> Pass Disease and Infection constructor arguments to parent

CHANGELOG.rst, starsim/demographics.py, starsim/disease.py, starsim/network.py, starsim/parameters.py, starsim/sim.py, starsim/version.py, tests/test_diseases.py, tests/test_syphilis.py
Separates maternal transmission into prenatal and postnatal modules.
This is necessary because transmission probabilities vary. We could alternatively change the network betas, but this way allows us more flexibility to have disease-dependent differences - e.g. maternal transmission of syphilis only occurs during pregnancy, whereas for HIV it can also happen during breastfeeding.
=> Prenatal and postnatal transmission

starsim/diseases/sir.py, tests/test_vaccine.py
Extend the sir_vaccine to support all_or_nothing (i.e. some vaccinated individuals are not susceptible whilst vaccine completely fails in others) as well as leaky (i.e. susceptibility in all vaccinated individuals reduced by the efficacy).
Added tests for the new all_or_nothing feature and the previous leaky behaviour.
=> Add option of sir_vaccine to be leaky or all_or_nothing

starsim/distributions.py
Fixes the issue where some `Dist` objects were being found first in the `People._states` object, which gets keys assigned based on object ID, which are effectively random, making results non-reproducible. Closes #533 and #534.
† I didn't add a test here; one could potentially loop through `sim.dists.dists` and test each RNG. But I think that test also wouldn't have caught this if implemented on a standard sim: if results are non-reproducible at that level, then `test_baselines.py` will fail.
=> Fix Dist initialization

CHANGELOG.rst, starsim/network.py, starsim/people.py, starsim/states.py, starsim/version.py
Minor changes to the `Arr` API. Main differences:
- `isnan` returns a `BoolArr` facilitating operations like `(self.cd4.isnan & self.infected).uids`
- Added operators to `uids` to facilitate set operations
=> Arr API tweaks

starsim/states.py
This addresses an unusual bug that arises when performing logical operations on a `uids` object, which is a subclass of `np.ndarray` - in that case, the use of `np.empty_like` causes the resulting `BoolArr` to have `uids` as the underlying type for the `raw` attribute rather than an `np.ndarray`. A subsequent logical operation will then use operators from `uids` rather than `np.ndarray`. This change uses `np.empty` rather than `np.empty_like` to ensure that the `raw` attribute is a bare `np.ndarray`
=> Ensure returned Arr has np.array type

starsim/demographics.py
This prevents warnings/errors raised on certain platforms due to operating on uninitialized entries from `np.empty` - these entries are present to allow indexing the array by UID and aren't used for anything, so this doesn't affect any results, but are causing STIsim's tests to fail on Linux. Using `np.zeros` to initialize those entries resolves the issue
=> Initialize fertility rate explicitly

CHANGELOG.rst, starsim/disease.py, starsim/modules.py, starsim/version.py, tests/test_diseases.py
This PR changes `log` from an argument of `Disease` to being part of the pars, so that it can be passed more easily through inheritance and handled alongside any other module settings. The `InfectionLog` is still created so that it can be used by custom code even if standard logging is not enabled (this is what STIsim does) but entries are only added to it by Starsim if `log=True`
=> Logging off by default

starsim/distributions.py
This PR updates the `dtype` of the `randint`-Distribution from `int` to `ss.dtypes.int (= numpy.int64)`.
Main returns an error when running on my local mashine that `high` is out of bounds, because it is assumed to be of type `int32`.
=> Update dtype of randint distribution

starsim/states.py
Fixes #502 - importantly, when testing this, it's necessary to check for in-place operations working on `Arr` instances where some of the agents are dead, to make sure that the result of the in-place operation is written back to the correct indices in `Arr.raw`. Accordingly, this is the test I've been using:
```python
import starsim as ss
import numpy as np
import sciris as sc
uids = ss.IndexArr()
uids.grow(np.arange(8))
people = sc.objdict(uid=uids, auids=np.array([1,3,5,7]))
x = ss.FloatArr(people=people)
x[:] = 1
print(x)
print(x.raw)
x += 1
print(x)
print(x.raw)
x[ss.uids([1,3])] += 1
print(x)
print(x.raw)
print(x + 1)
print(x + [10,10,10,10])
print(x[ss.uids([1,3])] + [5,5])
print(x+x)
```
=> Inplace fix

starsim/demographics.py, starsim/utils.py, tests/test_randomness.py
Fixing demographics so that users can override the fertility rate parameter even if using a subclass. Now `self.pars.p_fertility` in `init_pre` rather than doing everything in `__init__`.
Also changing `uint64` to signed `int64` in test_randomness.
=> Improving pregnancy configuration and fixing test_randomness

starsim/demographics.py
- Interpolate ASFR data to 1-year increments in `standardize_fertility_data()`
- Update initial `new_rates` in line 320 to shallow copy of the data to avoid re-assigning properties to the source object
- Remove `new_rates` assignment in 335 as `np.divide` stores results to `new_rates` automatically
=> Interpolate asfr

starsim/people.py, tests/test_other.py
Nominally addresses issue #616 on vestigial BasePeople comments after merge with People for 0.5.0 release.
Please check that the wording in people.py docstring of People is an accurate representation, or if we prefer just to drop that whole second paragraph.
=> scrub BasePeople vestigial comments

starsim/diseases/syphilis.py, starsim/distributions.py, starsim/products.py, tests/test_randomness.py
Makes the changes to `jump` discussed on the call -- which already caught two bugs in the code (both of which were due to ancient holdovers from the `MultiRNG` days).
If these changes look good, I'll backport `jump_dt()` and the updated `jump()` to Starsim v1.0.
=> Make jump robust

starsim/calibration.py, tests/test_calibration.py
- In `test_calibration.py`:
- Super tiny fix: moves line that could  have resulted in an error or a mistake for 'rand_seed', depending on the order of keys in calib parameters.
- Fix path to parameters in `calib_pars`
- In `calibration.py`: 
- Remove `rand_seed` from `calib_pars` before self.build_fn is called. `rand_seed`'s value is an int not a dict like for the rest of the calib parameters
=> Tiny fixes in test calib and calibration

starsim/samples.py, tests/test_samples.py
Retrieving items from a samples object causes a Value Error `ValueError: Index t invalid` in `samples.py` in line 390. 
Example: Retrieving an item in `test_samples()` in `test_samples.py`: 
```
outputs = get_outputs(0.2)
resultsdir = tempdir/'samples_results'
resultsdir.mkdir(exist_ok=True)
s = ss.Samples.new(resultsdir, outputs, identifiers=["p_death"])
s[0]
```
This was likely missed in the starsim 2.0 update and is fixed by updating from `t` to `timevec`.
=> Small bug in samples class when retrieving items 

docs/tutorials/tut_calibration.ipynb, starsim/calib_components.py, starsim/calibration.py, starsim/networks.py, tests/test_calibration.py
* Adding a 'none' conformer that bypasses conforming - addresses #850
* Separated combining replicates from bootstrapping. The default combine_reps is now None, which bypasses combining replicates.
* Now taking the mean across replicates instead of the sum. This change is important if using the `include_fn` and some replicates are rejected, resulting in a varying number of replicates across input parameter sets. The mean is the right operation here, not the sum.
* Fix a bug that was causing check_fit to do 4 replicates even when the user did not ask for replicates.
* Re-enabling calibration tests.
Avoids converting ss.beta to "values" before multiplying computing transmission, partly addressing #846.
=> Rc2.3 calib betafix

docs/tutorials/tut_calibration.ipynb, starsim/calib_components.py, starsim/calibration.py, starsim/networks.py, starsim/parameters.py, tests/test_calibration.py
Adds a flag `continue_db` to calibration. Also allows the user to save calibration results using `save_csv`.
Also addresses #826
=> Rc2.3 calib

starsim/time.py
Implements suggestion in https://github.com/starsimhub/starsim/issues/804 to implement logic within `Time.now()`
=> Support negative ti in Time.now(), closes #804

starsim/parameters.py
Fixes #891. Just needed to remove .par from the object paths in the error message of validate_verbose().
=> Removed .par from validate_verbose error msg

starsim/sim.py
If full_label is too long to display (i.e. len(res.full_label) > show_module) and res.label is None, display res.name. This mirrors the behaviour of Result.full_label(), and avoids displaying blank plot titles for results that have not been assigned a label.
^^^Very minor update, no new docstrings, tests or versions needed.
=> Display result name if result label is None

starsim/arrays.py, tests/test_other.py
Support indexing using boolean arrays the same size as `auids` (so that logical operations on `.values` can be used directly again to index other `Arr` instances)
=> Allow indexing Arr instances with boolean arrays

starsim/networks.py
The previous default value of 0.2 was useful for the previous configuration in which the MixingPool beta was used directly in transmission. Now, that the MixingPool beta is a multiplier on the disease beta, the default value should be 1.0.
=> Restore MixingPool beta to 1.0 now that it is interpreted as a multiplier

starsim/time.py
A couple speed ups:
They rely on the fact that `pd.Timestamp` is immutable, and we can change from a `pd.Timestamp` to a `ss.date` by calling `ss.date._reset_class(timestamp)`. This means when we create a pd.Timestamp in the functions `ss.date.from_year()` and `ss.date.__add__()` we don't need to copy the `pd.Timestamp` we get (which would happen in `ss.date.__new__()` ) - we only need to convert it from `pd.Timestamp` into a `ss.date` .
The other change is to not re-create the `ss.Time._yearvec` and `ss.Time._tvec` of each module if it is the same `start, stop, dt` as the `sim.t` - we can just create a copy. I guess this could break if the `sim.t` was initialized - then any of the `sim.t.start, sim.t.stop, sim.t.dt, sim.t._yearvec, sim.t._tvec` were then manually changed without …
=> Speed up time.py slightly

README.md, llms.txt, pyproject.toml
Closes #907
- Fixed numba dependency version requirement to `>=0.57.0` (resolves #902)
- Enhanced README with practical uv usage examples including `uv run` and dev dependencies
- Updated CLAUDE.md with uv installation instructions
- Tested uv installation works correctly with all dependencies
=> Add official uv support

starsim/time.py, tests/test_time.py
Hi @cliffckerr 
As per the commit messages
First commit is just adding error messages
The second commit fixes https://github.com/starsimhub/starsim/issues/968
Third commit speeds up DateDur._round_duration but does it exactly the same way
4th commit is faster way of multiplying a Rate * Dur but failed tests because it slightly changed some of the rounding
5th commit reverts 4th
6th commit adds tests for https://github.com/starsimhub/starsim/issues/968
Passes test_time.py
=> Refactor / Speed up time.py a little more

starsim/arrays.py
Hi @cliffckerr 
Sorry this PR is into your working branch because it involves the `nb_indexer`.
Changes are
- Add the check for the `_numba_threshold` to `Arr.grow` so that `People.slot` can also use the `nb_indexer` (previously it wasn't because it doesn't get `link_people` called.
- Remove the if statement in `Arr._index` by splitting into two wrappers `Arr._np_index, _nb_index` (need to wrap because of that sciris issue)
But its a bit faster (mainly because `slot` can use `nb_indexer`) and a bit neater
=> Refactor arrays.py slightly

CHANGELOG.rst, starsim/disease.py, starsim/version.py
`Infection.infect` isn't passing the optional `disease` argument to `route.net_beta` which causes a problem if the user inherits from `Infection` and then implements a network that requires the `disease` as part of it's `net_beta` implementation
=> Add missing argument
